/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {
        BMI bmiCalculator = new BMI();
        double burakBmi = bmiCalculator.calculateBMI(1.75, 73);
        System.out.println(burakBmi);
    }
}
